### ISSUE TITLE
  [taskdef] Could not load definitions from resource flexTasks.tasks. It could not be found.

### ISSUE THREAD

**Issue by simkimsia** [drewbourne/mockolate#63]
I ran ant clean package after i did a git clone.

I get the following errors

Buildfile: /Users/simkimsia/Desktop/Adobe-AIR-App-Skinning/vendors/mockolate/build.xml
  [taskdef] Could not load definitions from resource flexTasks.tasks. It could not be found.

clean:
   [delete] Deleting directory /Users/simkimsia/Desktop/Adobe-AIR-App-Skinning/vendors/mockolate/target

initialize-directories:
    [mkdir] Created dir: /Users/simkimsia/Desktop/Adobe-AIR-App-Skinning/vendors/mockolate/target
    [mkdir] Created dir: /Users/simkimsia/Desktop/Adobe-AIR-App-Skinning/vendors/mockolate/target/bin
    [mkdir] Created dir: /Users/simkimsia/Desktop/Adobe-AIR-App-Skinning/vendors/mockolate/target/docs
    [mkdir] Created dir: /Users/simkimsia/Desktop/Adobe-AIR-App-Skinning/vendors/mockolate/target/report
    [mkdir] Created dir: /Users/simkimsia/Desktop/Adobe-AIR-App-Skinning/vendors/mockolate/target/report/flexunit

initialize-properties:

initialize-build-configuration:

BUILD FAILED
/Users/simkimsia/Desktop/Adobe-AIR-App-Skinning/vendors/mockolate/build.xml:79: Java returned: 1

Please help.

Thank you.

**Comment by drewbourne** [comment]
Aha, hidden dependency.

You need to define a FLEX_HOME environment variable that points to the Flex
SDK directory.
In your ~/.bash_profile add a line like:

```
set FLEX_HOME=/Applications/Adobe\ Flash\ Builder\ 4.5/sdks/3.5.0/
```

(This is from memory, the path may not be 100% correct)

On Tue, Jun 5, 2012 at 9:18 PM, simkimsia <
reply@reply.github.com

**Comment by Bautastein** [comment]
I have exactly the same issue. After setting the environment variable as suggested, the problem persists. Mac OS X 10.7.5

I set the FLEX_HOME variable to the path where the SDK is located on the hard disk.

Bautasteins-MacBook-Pro:mockolate pbholmen$ echo $FLEX_HOME
/Applications/Adobe Flash Builder 4.6/sdks/4.6.0/
Bautasteins-MacBook-Pro:mockolate pbholmen$ sudo ant clean package
Password:
Buildfile: /Users/pbholmen/Documents/Adobe Flash Builder 4.6/mockolate/build.xml
  [taskdef] Could not load definitions from resource flexTasks.tasks. It could not be found.

clean:
   [delete] Deleting directory /Users/pbholmen/Documents/Adobe Flash Builder 4.6/mockolate/target

initialize-directories:
    [mkdir] Created dir: /Users/pbholmen/Documents/Adobe Flash Builder 4.6/mockolate/target
    [mkdir] Created dir: /Users/pbholmen/Documents/Adobe Flash Builder 4.6/mockolate/target/bin
    [mkdir] Created dir: /Users/pbholmen/Documents/Adobe Flash Builder 4.6/mockolate/target/docs
    [mkdir] Created dir: /Users/pbholmen/Documents/Adobe Flash Builder 4.6/mockolate/target/report
    [mkdir] Created dir: /Users/pbholmen/Documents/Adobe Flash Builder 4.6/mockolate/target/report/flexunit

initialize-properties:

initialize-build-configuration:

BUILD FAILED
/Users/pbholmen/Documents/Adobe Flash Builder 4.6/mockolate/build.xml:79: Java returned: 1

Total time: 1 second
Bautasteins-MacBook-Pro:mockolate pbholmen$ ls /Applications/Adobe\ Flash\ Builder\ 4.6/sdks/4.6.0/
AIR SDK Readme.txt      asdoc               frameworks          lib             license-mpl.htm         samples
AIR SDK license.pdf     bin             include             license-adobesdk-fr.htm     readme.htm          templates
ant             flex-sdk-description.xml    install             license-adobesdk.htm        runtimes

**Comment by Bautastein** [comment]
PS: I don't know much about shells. I cloned the project just a few minutes ago, and I didn't have a ~/.bash_profile, so I edited ~/.profile instead, and used "export" instead of "set", because that's what was used in that file for other variables. But the result of echo $FLEX_HOME should indicate that the variable is correctly set?

**Comment by Bautastein** [comment]
Does it matter that I have Java 1.6? Here is the verbose output (I have double checke that $FLEX_HOME is set in the shell):

Bautasteins-MacBook-Pro:mockolate pbholmen$ sudo ant -v clean package
Apache Ant(TM) version 1.8.2 compiled on June 3 2011
Trying the default build file: build.xml
Buildfile: /Users/pbholmen/Documents/Adobe Flash Builder 4.6/mockolate/build.xml
Detected Java version: 1.6 in: /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
Detected OS: Mac OS X
parsing buildfile /Users/pbholmen/Documents/Adobe Flash Builder 4.6/mockolate/build.xml with URI = file:/Users/pbholmen/Documents/Adobe%20Flash%20Builder%204.6/mockolate/build.xml
Project base dir set to: /Users/pbholmen/Documents/Adobe Flash Builder 4.6/mockolate
parsing buildfile jar:file:/usr/share/ant/lib/ant.jar!/org/apache/tools/ant/antlib.xml with URI = jar:file:/usr/share/ant/lib/ant.jar!/org/apache/tools/ant/antlib.xml from a zip file
 [property] Loading Environment env.
 [property] Loading /Users/pbholmen/Documents/Adobe Flash Builder 4.6/mockolate/build/build.properties
Property "env.FLEX_HOME" has not been set
dropping /Users/pbholmen/Documents/Adobe Flash Builder 4.6/mockolate/${env.FLEX_HOME}/ant/lib/flexTasks.jar from path as it doesn't exist
  [taskdef] Could not load definitions from resource flexTasks.tasks. It could not be found.
 [macrodef] creating macro  compile-library
Build sequence for target(s) `clean' is [clean]
Complete build sequence is [clean, initialize-directories, initialize-properties, initialize-build-configuration, initialize-build-number, initialize-classes, initialize, compile.library.check-if-required, compile.library, compile, compile.test.check-if-required, compile.test, test.execute, report, pmd, test, docs, package, ]

clean:
   [delete] Deleting directory /Users/pbholmen/Documents/Adobe Flash Builder 4.6/mockolate/target
   [delete] Deleting directory /Users/pbholmen/Documents/Adobe Flash Builder 4.6/mockolate/target/bin
   [delete] Deleting directory /Users/pbholmen/Documents/Adobe Flash Builder 4.6/mockolate/target/docs
   [delete] Deleting directory /Users/pbholmen/Documents/Adobe Flash Builder 4.6/mockolate/target/report/flexunit
   [delete] Deleting directory /Users/pbholmen/Documents/Adobe Flash Builder 4.6/mockolate/target/report
   [delete] Deleting directory /Users/pbholmen/Documents/Adobe Flash Builder 4.6/mockolate/target
Build sequence for target(s) `package' is [initialize-directories, initialize-properties, initialize-build-configuration, initialize-build-number, initialize-classes, initialize, compile.library.check-if-required, compile.library, compile, compile.test.check-if-required, compile.test, test.execute, report, pmd, test, docs, package]
Complete build sequence is [initialize-directories, initialize-properties, initialize-build-configuration, initialize-build-number, initialize-classes, initialize, compile.library.check-if-required, compile.library, compile, compile.test.check-if-required, compile.test, test.execute, report, pmd, test, docs, package, clean, ]

initialize-directories:
    [mkdir] Created dir: /Users/pbholmen/Documents/Adobe Flash Builder 4.6/mockolate/target
    [mkdir] Created dir: /Users/pbholmen/Documents/Adobe Flash Builder 4.6/mockolate/target/bin
    [mkdir] Created dir: /Users/pbholmen/Documents/Adobe Flash Builder 4.6/mockolate/target/docs
    [mkdir] Created dir: /Users/pbholmen/Documents/Adobe Flash Builder 4.6/mockolate/target/report
    [mkdir] Created dir: /Users/pbholmen/Documents/Adobe Flash Builder 4.6/mockolate/target/report/flexunit

initialize-properties:

initialize-build-configuration:
     [java] Executing '/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/bin/java' with arguments:
     [java] '-jar'
     [java] '/Users/pbholmen/Documents/Adobe Flash Builder 4.6/mockolate/${env.FLEX_HOME}/lib/compc.jar'
     [java] '-version'
     [java] 
     [java] The ' characters around the executable and arguments are
     [java] not part of the command.
     [java] Output redirected to property: build.sdk.version

BUILD FAILED
/Users/pbholmen/Documents/Adobe Flash Builder 4.6/mockolate/build.xml:79: Java returned: 1
    at org.apache.tools.ant.taskdefs.Java.execute(Java.java:111)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.Target.execute(Target.java:390)
    at org.apache.tools.ant.Target.performTasks(Target.java:411)
    at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
    at org.apache.tools.ant.Project.executeTarget(Project.java:1368)
    at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
    at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
    at org.apache.tools.ant.Main.runBuild(Main.java:809)
    at org.apache.tools.ant.Main.startAnt(Main.java:217)
    at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
    at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)

Total time: 1 second
